This file serves as a playground file to read and visualized the data

normalize first, then add padding

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from os.path import join
import os
import sys

data_dir = "/home/icip_2025/data"

In [2]:
imagenet_mean = np.array([0.485, 0.456, 0.406])[np.newaxis, np.newaxis, ...]
im = np.zeros((640, 1000, 3))

In [3]:
im - imagenet_mean

array([[[-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        ...,
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406]],

       [[-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        ...,
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406]],

       [[-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        ...,
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406]],

       ...,

       [[-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        ...,
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406]],

       [[-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        [-0.485, -0.456, -0.406],
        .

In [37]:
train_dir = join(data_dir, "train")

datasets = os.listdir(train_dir)

shape = None

sizes = []

for dataset in datasets:
    dataset_path = join(train_dir, dataset)
    dataset_images = os.listdir(dataset_path)

    for image_name in dataset_images:
        image_path = join(dataset_path, image_name)
        image = plt.imread(image_path)

        s = image.shape
        s = s if s[1] / s[0] > 1 else (s[1], s[0], 3)
        sizes.append(s)

        # if shape is None:
        #     shape = image.shape
        # elif image.shape != shape:
        #     print(shape, image.shape)
        #     # sys.exit("Shapes are inconsistent")



In [38]:
sizes = np.array(sizes)

In [39]:
sizes.mean(axis = 0), sizes.min(axis = 0), sizes.max(axis = 0), np.median(sizes, axis = 0)

(array([ 849.13984576, 1235.15526992,    3.        ]),
 array([117, 204,   3]),
 array([4032, 6048,    3]),
 array([ 700., 1024.,    3.]))

In [57]:
aspect_ratios = sizes[:, 1] / sizes[:, 0]

In [58]:
aspect_ratios.var()

np.float64(0.03882707177657215)

In [59]:
plt.hist(aspect_ratio, bins = 10)

NameError: name 'aspect_ratio' is not defined

In [67]:
sizes[(sizes[:, 1] * sizes[:, 0]).argsort()[int(sizes.shape[0] * 0.9)]]

array([1200, 1200,    3])

In [55]:
1077 / 583

1.8473413379073755

In [4]:
import os
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import torchvision.transforms.functional as F
import torch
from torchvision import transforms

ModuleNotFoundError: No module named 'pandas'